services:
  ollama:
    container_name: ollama-service
    image: ollama/ollama:0.3.13
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/./ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped


volumes:
  ollama_data: